### PR TITLE
Use never as default player collision

### PR DESCRIPTION
**Pull request by StamBoom**
Use never as default player collision

### CODE REVIEW

**Comment by MylesIsCool** [comment]
Not sure about this change because anyone who isn't in a team will have collisions?

**Comment by StamBoom** [comment]
Yeah but the problem now is, 1.8 can push 1.9 users and 1.9 users can't push 1.8 users

**Comment by StamBoom** [comment]
But yeah, it's true. We probably should put everyone in a team while joining until some plugin changes it.

**Comment by Paulomart** [comment]
I think this would be up to the server owner. We could add an option to add everyone on the server into one team..

**Comment by Johandrex** [comment]
So why were this closed?

**Comment by MylesIsCool** [comment]
It was decided that this patch would not be beneficial I believe, it'll be redone soon no doubt.

**Comment by Johandrex** [comment]
Awesome, will donate then ;)

**Pull request closed without merging**
