### PR TITLE
Fix piston tile entity crash

### PR DESCRIPTION
**Pull request by Matsv**

### CODE REVIEW

**Comment by MylesIsCool** [comment]
<3

**Comment by PhanaticD** [comment]
still get crashed

**Comment by Matsv** [comment]
This is a client sided bug sadly. You can use the build on the build server that provides a config option to rewrite the piston extension. We'll have to wait and see if mojang will patch it next version.

**Comment by PhanaticD** [comment]
it still crashes with replace-pistons: true

**Comment by Matsv** [comment]
Could you pastebin your crashlog?

**Comment by PhanaticD** [comment]
http://pastebin.com/cVHfkv1b

looks like they were invisible piston heads to keep sand from falling when the hub was made in 1.7, i replaced them with barriers and no more crash

**Comment by Matsv** [comment]
Great to hear that :)

**Comment by ridalarry** [comment]
the issue still exist if there is a block with id 36 which I use to block the water from flowing on my hub server portals

**Comment by TiTo-418** [comment]
@ridalarry Replace them with barrier blocks

**Comment by Rida94** [comment]
@TiTo-418 I cant barriers will prevent the players from going in the portal

**Pull request merged**
