### PR TITLE
[WIP] Add bStats as a metrics service, implements #658

### PR DESCRIPTION
**Pull request by MiniDigger**
# Info

As explained in #658 bStats is basically the replacement for mcstats.org.

This pr implements the metric service for all 3 platforms and also adds a custom chart to track protocol versions of connected players. 
You will have to sign up @ bstats.org, add the plugin and configure the custom graph (its a 'Advanced Pie' named 'protocol_versions'), see [here](https://bstats.org/add-plugin) and [here](https://bstats.org/help/custom-charts)

# What data will be send?
From bStats.org:
```
By default, bStats sends the following data:
- Your server's randomly generated UUID
- The amount of players on your server
- The online mode of your server
- The bukkit version of your server
- The java version of your system (e.g. Java 8)
- The name of your OS (e.g. Windows)
- The version of your OS
- The architecture of your OS (e.g. amd64)
- The system cores of your OS (e.g. 8)
- bStats-supported plugins
- Plugin version of bStats-supported plugins
```
this PR will additional send the protocol version of all connected players.

All data collection can be disabled by the server admin by opting out in the bStats config: plugins/bStats/config.yml 

# Status
This PR is currently completely untested as I cannot build via (see gitter).  
Once that is fixed, I need to test all platforms with multiple versions.  
I am also unsure if the relocation works like that. Needs testing once I can build.

### CODE REVIEW

**Comment by MiniDigger** [comment]
oh yeah, ill rebase and test stuff later today.

**Comment by Matsv** [comment]
My opinion about it:
It's currently not possible to disable it. Not everyone likes to have it enabled. 
I never really like to have built-in metrics, but that's me. 
It's up to @MylesIsCool to implement it or not :)

**Comment by MiniDigger** [comment]
as I mentioned, you can disable it globally for the whole server, but I don't mind adding an option in the config to disable it.

**Comment by Matsv** [comment]
@MiniDigger Ah sorry, I missed that (:

**Comment by MylesIsCool** [comment]
We've taken the decision to decline this PR, see the related issue for further explanation, #658.

**Pull request closed without merging**
