### PR TITLE
Added that fancy message when 1.9 clients try to enter a Minecart or Boat

### PR DESCRIPTION
**Pull request by fillefilip8**
Here you go :)

### CODE REVIEW

**Comment by StamBoom** [comment]
Minecarts does work. The only thing that does not work yet is leaving it (You'll stay inside the minecart client-sided)

**Comment by fillefilip8** [comment]
I noticed that now :)

**Comment by StamBoom** [comment]
:+1:

**Comment by fillefilip8** [comment]
Well on the spigot page it says  "(Probably won't be fixed due to them being changed in 1.9, we'll add a fancy message soon!)"
So i added a fancy message :) Haha

**Comment by fillefilip8** [comment]
Adding that message can be a placeholder until a real fix comes out (if you guys decide to make it work)

**Comment by MylesIsCool** [comment]
If we don't have anything towards Minecarts / Boats being properly fixed by the end of the day I'll pull this change as we should notify them.

This won't be long term as hopefully we will get it done.


Thanks,

Myles

**Comment by StamBoom** [comment]
#83

**Comment by fillefilip8** [comment]
^

**Pull request closed without merging**
