### PR TITLE
Implement new protocol version registry

### PR DESCRIPTION
**Pull request by HugoDaBosss**
Should credit @Matsv as well for creating the ProtocolVersion class ;)

### CODE REVIEW

**Comment by Matsv** [comment]
:+1:

**Comment by Matsv** [comment]
@HugoDaBosss Totally not testing Hugo's notifications

**Comment by HugoDaBosss** [comment]
And I should ALSO credit @Matsv for his typo ;)

**Comment by Matsv** [comment]
:heart:

**Pull request merged**
